### ISSUE TITLE
[Bug] Unable to run pacaptr on macOS 11.0.1

### ISSUE THREAD

**Issue by xMuu** [rami3l/pacaptr#40]
I got this after I run it:
```
bash-3.2$ pacaptr -h
Killed: 9
```

I installed pacaptr from Homebrew and the version of pacaptr is v0.8.0.

**Comment by rami3l** [comment]
After seeing https://github.com/astefanutti/kubebox/issues/105, I believe that this is a problem with UPX during the distribution process. The original binary seems fine.
What's more, because GitHub Actions haven't update its runners to macOS 11 yet, I have failed to detect this problem.
I'll stop using UPX at least for now.

**Comment by rami3l** [comment]
Closed in https://github.com/rami3l/pacaptr/commit/4b263d9b2bcd3ea72cead474db28d3e97e5babc8.
