### ISSUE TITLE
[Feature Request] Add scoop support

### ISSUE THREAD

**Issue by Eyepan** [rami3l/pacaptr#73]
[Hello. Most of us are using the scoop package manager. And as a person who came from using Arch most of the time I would love to have that syntax while using scoop. Thanking in advance

Link to scoop: [HERE](https://scoop.sh)

**Comment by rami3l** [comment]
@Eyepan Thank you for your suggestion!

I'll be doing this very soon. Just one question: do you use the `--global` flag often? Is it okay to just leave it alone and make you pass it by `-- --global` at the end of the command?

Actually, support for `scoop` has been on the waiting list for a long time. I made some research, but since I personally don't use scoop, if I make such an implementation, I won't be able to verify if it is the right mapping. Also, it seems that scoop is rather simple, so not many commands will be mapped. Sorry about that.

If you know about Rust, don't hesitate to propose some test cases for the implementation!

**Comment by Eyepan** [comment]
1. Yes I and I'm assuming most others use `--global` always since Windows is always screwing around with default apps and setting them is honestly a PITA.

2. Yeah I don't have a problem with not many commands being mapped with scoop, I just want to use `pacman -S`, `pacman -Syu`, `pacman -Q` and stuff like that, since I and most others grew a habit of using that mostly.

3. I am sorry, I have yet to learn Rust, so I can't be of much help to you. Thank you and all the very best in coding dude!

**Comment by rami3l** [comment]
@Eyepan I tried my best, but it seems I am blocked by https://github.com/lukesampson/scoop/issues/3749. :(

**Comment by Eyepan** [comment]
Oh no that's sad. I wonder why they did that.

As for the hack, hey if it works then it's perfect enough! 😂 

But yeah can't wait to use this dude!
With excitement, Pan

**Comment by rami3l** [comment]
@Eyepan The hack does work on my virtual machine (my daily driver is not a Windows PC right now), but I somehow failed to convince the GitHub CI....

BTW as I have stated in the [README](https://github.com/rami3l/pacaptr#general-tips), you can always pass extra flags to the underlying package manager, eg. `pacaptr --using scoop -S curl -- --global`.

**Comment by rami3l** [comment]
@Eyepan I finally got this feature to work with no runtime errors popping up (they are mostly due to the fact that `scoop` is a script rather than a binary), though the Rosetta table might still be wrong.

Feel free to try the new version yourself and if you have any problems, don't hesitate to ask :)
